apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.vmctl.name }}
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 600
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - us-west-2b
      containers:
      - name: vmctl
        image: "{{ .Values.vmctl.image.repository }}:{{ .Values.vmctl.image.tag }}"
        imagePullPolicy: {{ .Values.vmctl.image.pullPolicy }}
        args:
          - "vm-native"
          - "--vm-native-filter-time-start"
          - "{{ .Values.vmctl.timestamp }}"
          - "--vm-native-src-addr"
          - "{{ .Values.vmctl.sourceUrl }}"
          - "--vm-native-dst-addr"
          - "{{ .Values.vmctl.destUrl }}"
        resources:
{{ toYaml .Values.vmctl.resources | indent 10 }}
      restartPolicy: Never
