apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    service: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      imagePullSecrets:
        - name: docker-hub      
      containers:
      - name: mongodb
        image: {{ .Values.image.repo }}/robot-shop-rs-mongodb:{{ .Values.image.mongodbVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      - name: mongodb-exporter
        image: percona/mongodb_exporter:0.31.0
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: MONGODB_URI
            value: mongodb://mongodb:27017
        ports:
          - name: exporter
            containerPort: 9216
        args:
          - --collect-all
          - --compatible-mode
      restartPolicy: Always
