apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: payment
spec:
  endpoints:
    - path: /metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      service: payment