apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "asserts.grafanaFullname" . }}
  labels: {{- include "asserts.grafanaLabels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 -}}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
  {{- toYaml .Values.annotations | nindent 4 -}}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "asserts.grafanaSelectorLabels" . | nindent 6 }}
  serviceName: {{ include "asserts.grafanaFullname" . }}
  {{- if .Values.updateStrategy }}
  updateStrategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "asserts.grafanaLabels" . | nindent 8 }}
        {{- with .Values.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.extraPodAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "asserts.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: grafana
          image:  "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy | quote }}
          {{- with .Values.grafana.extraEnv }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.grafana.extraEnvFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.grafana.service.port }}
          resources: {{- toYaml .Values.grafana.resources | nindent 12 }}
          {{- with .Values.grafana.extraVolumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
  {{- if not .Values.grafana.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else if .Values.grafana.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.grafana.persistence.existingClaim }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: {{- include "asserts.grafanaLabels" . | nindent 10 }}
      spec:
        accessModes:
        {{- range .Values.grafana.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.grafana.persistence.size | quote }}
        {{ include "asserts.storageClass"  . }}
  {{- end }}
