replicas: 1

image:
  repository: asserts/aws-cloudwatch-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag:

service:
  aws:
    port: 8010

ingress:
  enabled: false

  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  # ingressClassName: nginx

  annotations: {}

  extraLabels: {}

  hosts: []
  #   - aws-exporter.domain.com

  path: /

  # pathType is only for k8s >= 1.18
  pathType: Prefix

  ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
  extraPaths: []
  # - path: /*
  #   backend:
  #     serviceName: ssl-redirect
  #     servicePort: use-annotation

  tls: []
  #   - secretName: aws-exporter-tls
  #     hosts:
  #       - aws-exporter.domain.com

env:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""

serviceMonitor:
  enabled: false
  endpoints:
    - port: aws
      path: /aws-exporter/actuator/prometheus

serviceAccount:
  create: true
