{{ if or (.Values.primary.configuration) (.Values.primary.pgHbaConfiguration) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "postgres.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 -}}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
  {{- toYaml .Values.annotations | nindent 4 -}}
  {{- end }}
data:
  {{- if .Values.primary.configuration }}
  postgresql.conf: |-
    {{- .Values.primary.configuration | nindent 4 }}
  {{- end }}
  {{- if .Values.primary.pgHbaConfiguration }}
  pg_hba.conf: |-
    {{- .Values.primary.pgHbaConfiguration | nindent 4 }}
  {{- end }}
{{- end }}

