apiVersion: v2
name: promxy
description: Helm Chart for Prometheus proxy to combine multiple prometheuses

type: application

version: 0.9.0
appVersion: v0.3.0

maintainers:
  - name: Asserts
    url: https://github.com/asserts
