apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "asserts.serverFullname" . }}-changelog
  labels: {{- include "asserts.serverLabels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 -}}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
  {{- toYaml .Values.annotations | nindent 4 -}}
  {{- end }}
data:
  changelog.yml: |-
    databaseChangeLog:
    - include:
        file: classpath:/db/changelog/db.changelog-master.yaml
    - property:
        name: tenant_graph.server
        value: asserts-redisgraph-master.{{ include "domain" . }}
    - property:
        name: tenant_search.server
        value: asserts-redisearch-master.{{ include "domain" . }}
    - property:
        name: tenant_tsdb.url
        value: http://{{ .Release.Name }}-promxy.{{ include "domain" . }}:8082
    - property:
        name: tenant_grafana.url
        value: http://{{ .Release.Name }}-grafana.{{ include "domain" . }}:3000

    - changeSet:
        id: k8s-1
        author: alex
        comment: 'Remove bootstrap tenant auth config'
        changes:
            - sql:
                dbms: 'postgresql'
                sql: >-
                DELETE FROM tenant_auth WHERE tenant_id = 'bootstrap';

    - changeSet:
        id: k8s-2
        author: alex
        comment: 'Update bootstrap graph'
        changes:
            - sql:
                dbms: 'postgresql'
                sql: >-
                UPDATE tenant_graph SET server = '${tenant_graph.server}', port = 6379, updated = NOW()
                    WHERE tenant_id = 'bootstrap';

    - changeSet:
        id: k8s-3
        author: alex
        comment: 'Update bootstrap search'
        changes:
            - sql:
                dbms: 'postgresql'
                sql: >-
                UPDATE tenant_search SET server = '${tenant_search.server}', port = 6379, updated = NOW()
                    WHERE tenant_id = 'bootstrap';

    - changeSet:
        id: k8s-4
        author: alex
        comment: 'Update bootstrap tsdb to promxy'
        changes:
            - sql:
                dbms: 'postgresql'
                sql: >-
                UPDATE tenant_tsdb SET url = '${tenant_tsdb.url}', updated = NOW()
                    WHERE tenant_id = 'bootstrap';

    - changeSet:
        id: k8s-5
        author: alex
        comment: 'Update bootstrap grafana'
        changes:
            - sql:
                dbms: 'postgresql'
                sql: >-
                UPDATE tenant_grafana SET url = '${tenant_grafana.url}', data_source = 'Prometheus', org_id = 1,
                    username = 'admin', password = 'dev', updated = NOW() WHERE tenant_id = 'bootstrap';
