apiVersion: v1
kind: Service
metadata:
  name: {{ include "asserts.serverFullname" . }}
  labels: {{- include "asserts.serverLabels" . | nindent 4 }}
    {{- with .Values.server.extraLabels }}
    {{- toYaml . | nindent 4 -}}
    {{- end }}
  {{- if .Values.server.service.annotations }}
  annotations: {{ include "common.tplvalues.render" ( dict "value" .Values.server.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      protocol: TCP
      name: http
  selector: {{- include "asserts.serverSelectorLabels" . | nindent 4 }}
