apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "asserts.serverFullname" . }}
  labels: {{- include "asserts.serverLabels" . | nindent 4 }}
    {{- with .Values.server.extraLabels }}
    {{- toYaml . | nindent 4 -}}
    {{- end }}
  {{- if .Values.server.annotations }}
  annotations:
  {{- toYaml . | nindent 4 -}}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "asserts.serverSelectorLabels" . | nindent 6 }}
  serviceName: {{ include "asserts.serverFullname" . }}
  {{- with .Values.server.updateStrategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "asserts.serverLabels" . | nindent 8 }}
        {{- with .Values.server.extraPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/server/configmap.yaml") . | sha256sum }}
        {{- with .Values.server.extraPodAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "asserts.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.server.terminationGracePeriodSeconds }}
      {{- if .Values.server.initContainers }}
      initContainers: {{ include "render-values" ( dict "value" .Values.server.initContainers "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy | quote }}
          {{- with .Values.server.extraEnv }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.extraEnvFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
          resources: {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /opt/asserts/api-server/conf/application.yml
              subPath: application.yml
              readOnly: true
          {{- with .Values.server.extraVolumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "asserts.serverFullname" . }}
            items:
              - key: application.yml
                path: application.yml
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  {{- if not .Values.server.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else if .Values.server.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.server.persistence.existingClaim }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: {{- include "asserts.serverLabels" . | nindent 10 }}
      spec:
        accessModes:
        {{- range .Values.server.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.server.persistence.size | quote }}
        {{ include "asserts.storageClass"  . }}
  {{- end }}
