{{- if .Values.vmselect_user.podDisruptionBudget.enabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1" }}
apiVersion: policy/v1beta1
{{- else -}}
apiVersion: policy/v1
{{- end -}}
kind: PodDisruptionBudget
metadata:
  name: {{ template "victoria-metrics.vmselect_user.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "victoria-metrics.vmselect_user.labels" . | nindent 4 }}
  {{- with .Values.vmselect_user.podDisruptionBudget.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.vmselect_user.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.vmselect_user.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.vmselect_user.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.vmselect_user.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      {{- include "victoria-metrics.vmselect_user.matchLabels" . | nindent 6 }}
{{- end }}
