{{- if and .Values.vmselect_user.enabled .Values.vmselect_user.statefulSet.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
{{- with .Values.vmselect_user.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "victoria-metrics.vmselect_user.labels" . | nindent 4 }}
{{- with .Values.vmselect_user.extraLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "victoria-metrics.vmselect_user.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ template "victoria-metrics.vmselect_user.fullname" . }}
  selector:
    matchLabels:
      {{- include "victoria-metrics.vmselect_user.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.vmselect_user.replicaCount }}
  podManagementPolicy: {{ .Values.vmselect_user.podManagementPolicy }}
  template:
    metadata:
    {{- if .Values.vmselect_user.podAnnotations }}
      annotations:
{{ toYaml .Values.vmselect_user.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "victoria-metrics.vmselect_user.labels" . | nindent 8 }}
{{- with .Values.vmselect_user.extraLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
{{- if .Values.vmselect_user.priorityClassName }}
      priorityClassName: "{{ .Values.vmselect_user.priorityClassName }}"
{{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
      {{- with .Values.vmselect_user.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "victoria-metrics.name" . }}-{{ .Values.vmselect_user.name }}
          image: "{{ .Values.vmselect_user.image.repository }}:{{ .Values.vmselect_user.image.tag }}"
          imagePullPolicy: "{{ .Values.vmselect_user.image.pullPolicy }}"
          {{- if .Values.vmselect_user.containerWorkingDir }}
          workingDir: {{ .Values.vmselect_user.containerWorkingDir }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.vmselect_user.podSecurityContext | nindent 12 }}
          args:
            - {{ printf "%s=%s" "--cacheDataPath" .Values.vmselect_user.cacheMountPath | quote}}
          {{- if not .Values.vmselect_user.suppresStorageFQDNsRender }}
          {{- include "victoria-metrics.vmselect_user.vmstorage-pod-fqdn" . | nindent 12 }}
          {{- end }}
          {{- include "victoria-metrics.vmselect_user.vmselect_user-pod-fqdn" . | nindent 12 -}}
          {{- range $key, $value := .Values.vmselect_user.extraArgs }}
            - --{{ $key }}={{ $value }}
          {{- end }}
          {{- with .Values.vmselect_user.env }}
          env: {{ toYaml . | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8481
          {{- if .Values.vmselect_user.extraArgs.clusternativeListenAddr }}
            - name: cluster-tcp
              protocol: TCP
              containerPort: {{ include "split-host-port" .Values.vmselect_user.extraArgs.clusternativeListenAddr }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: {{ .Values.vmselect_user.cacheMountPath }}
              name: cache-volume
            {{- range .Values.vmstorage.extraHostPathMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
            {{- with .Values.vmselect_user.extraVolumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.vmselect_user.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.vmselect_user.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
    {{- if .Values.vmselect_user.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.vmselect_user.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.vmselect_user.securityContext }}
      securityContext:
{{ toYaml .Values.vmselect_user.securityContext | indent 8 }}
    {{- end }}
      serviceAccountName: {{ template "victoria-metrics.serviceAccountName" . }}
    {{- if .Values.vmselect_user.tolerations }}
      tolerations:
{{ toYaml .Values.vmselect_user.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.vmselect_user.affinity }}
      affinity:
{{ toYaml .Values.vmselect_user.affinity | indent 8 }}
    {{- end }}
      volumes:
      {{- with .Values.vmselect_user.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if not .Values.vmselect_user.persistentVolume.enabled }}
      - name: cache-volume
        emptyDir: {}
      {{- end }}
  {{- if .Values.vmselect_user.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: cache-volume
        {{- if .Values.vmselect_user.persistentVolume.annotations }}
        annotations:
    {{ toYaml .Values.vmselect_user.persistentVolume.annotations | indent 10 }}
    {{- end }}
      spec:
        accessModes:
        {{ toYaml .Values.vmselect_user.persistentVolume.accessModes | indent 10 }}
        resources:
          requests:
            storage: "{{ .Values.vmselect_user.persistentVolume.size }}"
          {{- if .Values.vmselect_user.persistentVolume.storageClass }}
        {{- if (eq "-" .Values.vmselect_user.persistentVolume.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.vmselect_user.persistentVolume.storageClass }}"
        {{- end }}
        {{- end }}
{{- end }}
{{- end }}
