{{- if and .Values.vmselect_user.enabled .Values.vmselect_user.statefulSet.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.vmselect_user.statefulSet.service.annotations }}
  annotations:
{{ toYaml .Values.vmselect_user.statefulSet.service.annotations | indent 4}}
{{- end }}
  labels:
  {{- include "victoria-metrics.vmselect_user.labels" . | nindent 4 }}
{{- if .Values.vmselect_user.statefulSet.service.labels }}
{{ toYaml .Values.vmselect_user.statefulSet.service.labels | indent 4}}
{{- end }}
  name: {{ template "victoria-metrics.vmselect_user.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.vmselect_user.statefulSet.service.servicePort }}
      protocol: TCP
      targetPort: http
  {{- if .Values.vmselect_user.extraArgs.clusternativeListenAddr }}
    - name: cluster-tcp
      protocol: TCP
      port: {{ include "split-host-port" .Values.vmselect_user.extraArgs.clusternativeListenAddr }}
      targetPort: cluster-tcp
  {{- end }}
  selector:
    {{- include "victoria-metrics.vmselect_user.matchLabels" . | nindent 4 }}
{{- end -}}
