apiVersion: v2
name: kube-prometheus-stack
description: Asserts Helm Chart to configure kube-prometheus-stack

type: application

version: 0.3.0
appVersion: 0.54.0

dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 32.2.0

maintainers:
  - name: Asserts
    url: https://github.com/asserts
