apiVersion: v2
name: asserts
description: Asserts Helm Chart to configure entire asserts stack
icon: https://www.asserts.ai/favicon.png
type: application

version: 0.0.0-rancher

dependencies:
  ## asserts charts ##
  # local charts in asserts/charts
  - name: knowledge-sensor
    repository: https://asserts.github.io/helm-charts
    version: 1.0.0
    condition: knowledge-sensor.enabled
  - name: victoria-metrics-single
    repository: https://asserts.github.io/helm-charts
    version: 0.8.12
    condition: victoria-metrics-single.enabled
  - name: alertmanager
    repository: https://asserts.github.io/helm-charts
    version: 0.14.0
    condition: alertmanager.enabled
  - name: promxyruler
    repository: https://asserts.github.io/helm-charts
    version: 0.7.0
    condition: promxyruler.enabled
  - name: promxyuser
    repository: https://asserts.github.io/helm-charts
    version: 0.7.0
    condition: promxyuser.enabled
  - name: redisgraph
    repository: https://asserts.github.io/helm-charts
    version: 16.8.7
    condition: redisgraph.enabled
  - name: redisearch
    repository: https://asserts.github.io/helm-charts
    version: 16.8.7
    condition: redisearch.enabled
  ### external charts ###
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.23
    condition: postgresql.enabled

maintainers:
  - name: Asserts
    url: https://github.com/asserts
