apiVersion: v2
name: asserts
description: Asserts Helm Chart to configure entire asserts stack
icon: https://www.asserts.ai/favicon.png
type: application

version: 1.39.0

dependencies:
  ### asserts charts ###
  # local charts in asserts/charts
  - name: knowledge-sensor
    repository: https://asserts.github.io/helm-charts
    version: 1.1.0
    condition: knowledge-sensor.enabled
  - name: victoria-metrics-single
    repository: https://asserts.github.io/helm-charts
    version: 1.1.0
    alias: tsdb
    condition: tsdb.enabled
  - name: alertmanager
    repository: https://asserts.github.io/helm-charts
    version: 1.0.0
    condition: alertmanager.enabled
  - name: promxy
    repository: https://asserts.github.io/helm-charts
    version: 0.8.0
    alias: promxyruler
    condition: promxyruler.enabled
  - name: promxy
    repository: https://asserts.github.io/helm-charts
    version: 0.8.0
    alias: promxyuser
    condition: promxyuser.enabled
  - name: ebpf-probe
    repository: https://asserts.github.io/helm-charts
    version: 0.7.0
    alias: ebpfProbe
    condition: ebpfProbe.enabled
  ### external charts ###
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.13.2
    alias: redisgraph
    condition: redisgraph.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.13.2
    alias: redisearch
    condition: redisearch.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.13
    alias: postgres
    condition: postgres.enabled

maintainers:
  - name: Asserts
    url: https://github.com/asserts
