{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  {{ include "aws-exporter.fullname" . }}
  labels:
    {{- include "aws-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  {{- range $endpoint := .Values.serviceMonitor.endpoints }}
    - port: {{ $endpoint.port }}
  {{- if $endpoint.path }}
      path: {{ $endpoint.path }}
  {{- end }}
  {{- if $.Values.serviceMonitor.honorLabels }}
      honorLabels: {{ $.Values.serviceMonitor.honorLabels }}
  {{- end }}
  {{- if $.Values.serviceMonitor.interval }}
      interval: {{ $.Values.serviceMonitor.interval }}
  {{- end }}
  {{- if $.Values.serviceMonitor.timeout }}
      scrapeTimeout: {{ $.Values.serviceMonitor.timeout }}
  {{- end }}
{{- if $.Values.serviceMonitor.relabelings }}
      relabelings:
  {{ toYaml $.Values.serviceMonitor.relabelings | indent 6 }}
{{- end }}
{{- if $.Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ toYaml $.Values.serviceMonitor.metricRelabelings | indent 6 }}
{{- end }}
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "aws-exporter.selectorLabels" . | nindent 6 }}
{{- end }}