apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "model-builder.fullname" . }}
  labels:
    {{- include "model-builder.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "model-builder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "model-builder.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "model-builder.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /model-builder/ping
              port: http
          readinessProbe:
            httpGet:
              path: /model-builder/ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        
          volumeMounts:
          - name: app-config
            mountPath: "{{ .Values.volume.baseDir }}/application.yml"
            subPath: application.yml
            readOnly: true
          - name: rules-config
            mountPath: "{{ .Values.volume.baseDir }}/model_rules.yml"
            subPath: model_rules.yml
            readOnly: true

      volumes:
      - name: app-config
        configMap:
          name: {{ include "model-builder.fullname" . }}
      - name: rules-config
        configMap:
          name: {{ include "model-builder.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
