apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-collector.fullname" . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otel-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "otel-collector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "otel-collector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TRACE_STORE
              value: {{ .Values.traceStore }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: ASSERTS_SERVER_API_ENDPOINT
              value: {{ .Values.assertsApiEndpoint }}
            - name: ASSERTS_SERVER_USERNAME
              value: {{ .Values.assertsUser }}
            {{- if .Values.assertsPassword }}
            - name: ASSERTS_SERVER_PASSWORD
              value: {{ .Values.assertsPassword }}
            {{- end }}
            {{- if .Values.assertsEnv }}
            - name: ASSERTS_ENV
              value: {{ .Values.assertsEnv }}
            {{- end }}
            {{- if .Values.assertsSite }}
            - name: ASSERTS_SITE
              value: {{ .Values.assertsSite }}
            {{- end }}
            - name: ASSERTS_TENANT
              value: {{ .Values.assertsUser }}
            {{- if or (eq .Values.traceStore "OLTP") (eq .Values.traceStore "OLTP-HTTP") }}
            - name: OTLP_ENDPOINT
            {{- if .Values.jaeger.enabled }}
              value: http://{{.Chart.Name}}-jaeger-collector.{{.Release.Namespace}}.svc.cluster.local:4317
            {{- else }}
              value: {{ .Values.otlpEndpoint }}
            {{- end }}
            {{- end }}
            {{- if eq .Values.traceStore "GOOGLE-CLOUDTRACE" }}
            - name: GCP_PROJECT_NAME
              value: {{ .Values.gcpProjectName }}
            {{- end }}
          ports:
            {{- range $key, $port := .Values.ports }}
            {{- if $port.enabled }}
            - name: {{ $key }}
              containerPort: {{ $port.containerPort }}
              protocol: {{ $port.protocol }}
            {{- end }}
            {{- end }}
          # TODO: figure out which port to use for probes
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 13133
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 13133
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
