apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "$servicePort.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.collector.port }}
      targetPort: {{ .Values.service.collector.port }}
      name: collector
    - port: { { .Values.service.metric.port } }
      targetPort: { { .Values.service.metric.port } }
      name: metric
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}
