{{- if .Values.tenant.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tenant.name }}-victoria-metrics-single
  labels:
    tenant: {{ .Values.tenant.name }}
data:
  username: {{ .Values.tenant.name | b64enc | quote }}
  password: {{ .Values.tenant.password | b64enc | quote }}
{{- end }}
