{{- if .Values.alertmanager.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alertmanager.existingConfigMap }}
  labels: {{- include "asserts.labels" . | nindent 4 }}
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by:
        - sg
        - tenant
        - alertname
        - asserts_notification_rule_name
        - source_alertname
        - asserts_slo_name
        - namespace
      receiver: blackhole
      repeat_interval: 5m
      group_wait: 5s
      group_interval: 5s
      routes:
        # chief
        - receiver: {{ include "asserts.tenant" . }}-tenant
          matchers:
            - tenant="{{ include "asserts.tenant" . }}"
          group_wait: 5s
          group_interval: 5s
          routes:
            - receiver: {{ include "asserts.tenant" . }}-tenant
              matchers:
                - tenant="{{ include "asserts.tenant" . }}"
              group_wait: 5s
              group_interval: 5s
              # TODO: uncomment once we have figured out the whole config
              # continue: true
    receivers:
      - name: blackhole
      # tenant name
      - name: {{ include "asserts.tenant" . }}-tenant
        webhook_configs:
          - send_resolved: true
            url: http://{{ .Release.Name }}-server.{{ include "domain" . }}:8030/api-server/v4/prometheus-alerts?tenant={{ include "asserts.tenant"  . }}
  {{- range $key, $value := .Values.templates }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
