{{- $defaultSecret := .Values.postgres.global.postgresql.auth.existingSecret }}
{{- if and (not (empty $defaultSecret)) (eq $defaultSecret "asserts-default") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $defaultSecret }}
  labels: {{- include "asserts.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.defaultPassword | b64enc | quote }}
  password: {{ .Values.postgres.defaultPassword | b64enc | quote }}
  {{- if eq .Values.postgres.architecture "replication" }}
  replication-password: {{ .Values.defaultPassword | b64enc | quote }}
  {{- end }}
{{- end }}