{{- if .Values.promxy.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.promxy.existingConfigMap }}
  labels: {{- include "asserts.labels" . | nindent 4 }}
data:
  # ref: https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml
  config.yaml: |
    global:
      evaluation_interval: 30s
      # TODO: figure out if this external label is needed
      external_labels:
        tenant: {{ include "asserts.tenant" . }}
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - {{.Release.Name}}-alertmanager.{{ include "domain" . }}:9093
    promxy:
      server_groups:
        - anti_affinity: 10s
          http_client:
            dial_timeout: 1s
            tls_config:
              insecure_skip_verify: true
          ignore_error: true
          {{- if .Values.env }}
          labels:
            asserts_env: {{ .Values.env }}
            {{- if .Values.env }}
            asserts_site: {{ .Values.site }}
            {{- end }}
          {{- end }}
          query_params:
            nocache: 1
          remote_read: false
          scheme: {{ .Values.prometheus.scheme }}
          static_configs:
            - targets:
              - {{ .Values.prometheus.url }}
        - anti_affinity: 10s
          http_client:
            dial_timeout: 1s
            tls_config:
              insecure_skip_verify: true
          ignore_error: true
          query_params:
            nocache: 1
          remote_read: false
          scheme: http
          static_configs:
            - targets:
              - {{.Release.Name}}-tsdb-server.{{ include "domain" . }}:8428
    remote_write:
      - url: http://{{.Release.Name}}-tsdb-server.{{ include "domain" . }}:8428/api/v1/write
    rule_files:
      - /etc/asserts/rules/*.yml
{{- end }}
