{{- if .Values.promxy.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.promxy.existingConfigMap }}
  labels: {{- include "asserts.labels" . | nindent 4 }}
data:
  # ref: https://github.com/jacksontj/promxy/blob/master/cmd/promxy/config.yaml
  config.yaml: |
    global:
      evaluation_interval: 30s
      # TODO: figure out if this external label is needed (e.g. tenant: bootstrap)
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - {{.Release.Name}}-alertmanager.{{ include "domain" . }}:9093
    promxy:
      server_groups:
      # server configuration for each prometheus endpoint being queried
      {{ range $i, $endpoint := .Values.prometheusEndpoints }}
        - anti_affinity: 10s
          http_client:
            dial_timeout: 1s
            tls_config:
              insecure_skip_verify: true
          ignore_error: true
          {{- if $endpoint.env }}
          labels:
            asserts_env: {{ $endpoint.env }}
            {{- if $endpoint.site }}
            asserts_site: {{ $endpoint.site }}
            {{- end }}
          {{- end }}
          query_params:
            nocache: 1
          remote_read: false
          {{- if $endpoint.scheme }}
          scheme: {{ $endpoint.scheme }}
          {{- else }}
          scheme: http
          {{- end }}
          static_configs:
            - targets:
              - {{ $endpoint.url }}
      {{- end }}
      # server configuration for the Asserts Tsdb
        - anti_affinity: 10s
          http_client:
            dial_timeout: 1s
            tls_config:
              insecure_skip_verify: true
          ignore_error: true
          labels:
            # TODO: figure out is this is what we want the env to be
            asserts_env: dev
            asserts_site: dev
          query_params:
            nocache: 1
          remote_read: false
          scheme: http
          static_configs:
            - targets:
              - {{.Release.Name}}-tsdb-server.{{ include "domain" . }}:8428
    remote_write:
      - url: http://{{.Release.Name}}-tsdb-server.{{ include "domain" . }}:8428/api/v1/write
    rule_files:
      - /etc/asserts/rules/*.yml
{{- end }}
