apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-autoscalinggroup-activity-exporter.fullname" . }}
  labels:
    {{- include "aws-autoscalinggroup-activity-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl .Values.config . | nindent 4 }}
