apiVersion: v2
name: otel-collector
description: Asserts Opentelemetry Collector
type: application
version: 0.1.0
appVersion: v0.0.92-all-exporters

maintainers:
  - name: Asserts
    url: https://github.com/asserts

dependencies:
  - name: jaeger
    repository: https://jaegertracing.github.io/helm-charts
    version: 0.71.3
    condition: jaeger.enabled
