replicas: 1

image:
  repository: asserts/otel-collector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag:

service:
  collector:
    port: 4317
  metric:
    port: 9465

ingress:
  enabled: false

  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  # ingressClassName: nginx

  annotations: {}

  extraLabels: {}

  hosts: []
  #   - otel-collector.domain.com

  path: /

  # pathType is only for k8s >= 1.18
  pathType: Prefix

  ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
  extraPaths: []
  # - path: /*
  #   backend:
  #     serviceName: ssl-redirect
  #     servicePort: use-annotation

  tls: []
  #   - secretName: otel-collector-tls
  #     hosts:
  #       - otel-collector.domain.com

env:
  TRACE_STORE: "OTLP-HTTP"
  OTLP_ENDPOINT: ""
  ASSERTS_SERVER_API_ENDPOINT: ""
  ASSERTS_SERVER_USERNAME: ""
  ASSERTS_SERVER_PASSWORD: ""
  ASSERTS_ENV: ""
  ASSERTS_SITE: ""
  ASSERTS_TENANT: ""
  LOG_LEVEL: ""

serviceMonitor:
  enabled: false
  endpoints:
    - port: metric
      path: /metrics

serviceAccount:
  create: true
