name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # These are the kind node images representing the
        # k8s versions to be tested in the "Create kind cluster" step
        k8s-version:
          - kindest/node:v1.19.16@sha256:476cb3269232888437b61deca013832fee41f9f074f9bed79f57e4280f7c48b7
          - kindest/node:v1.22.15@sha256:7d9708c4b0873f0fe2e171e2b1b7f45ae89482617778c1c875f1053d4cef2e41

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.5.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          # skip knowledge-sensor test due to current service dependency
          # a rules api endpoint
          if [[ "${changed}" =~ "knowledge-sensor" ]]; then
            echo "skipping knowledge-sensor test..."
            echo "::set-output name=changed::false"
          elif [[ "${changed}" =~ "asserts" ]]; then
            echo "skipping asserts test..."
            echo "::set-output name=changed::false"
          elif [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          # https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1
          version: v0.11.1
          # node_image of the k8s-versions in strategy.matrix
          # block at the top of this file
          node_image: ${{ matrix.k8s-version }}
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
        if: steps.list-changed.outputs.changed == 'true'
